### ISSUE TITLE
Having some troubles implementing gsSlicer

### ISSUE THREAD

**Issue by Archerfortx** [gradientspace/gsSlicer#2]
Hi, I've been trying to test out your slicer in a windows form application.

Pretty basic one, just a button to generate a Gcode from the exemple given on your website : 

`
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

using g3;
using gs;
using gs.info;

namespace SlicingApp
{
    public partial class Form1 : Form
    {

        public static SingleMaterialFFFSettings LastSettings;

        public Form1()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            CappedCylinderGenerator cylgen = new CappedCylinderGenerator()
            {
                BaseRadius = 10,
                TopRadius = 5,
                Height = 20,
                Slices = 32
            };
            DMesh3 mesh = cylgen.Generate().MakeDMesh();
            MeshTransforms.ConvertYUpToZUp(mesh);       // g3 meshes are usually Y-up

            // center mesh above origin
            AxisAlignedBox3d bounds = mesh.CachedBounds;
            Vector3d baseCenterPt = bounds.Center - bounds.Extents.z * Vector3d.AxisZ;
            MeshTransforms.Translate(mesh, -baseCenterPt);

            PrintMeshAssembly meshes = new PrintMeshAssembly();
            meshes.AddMesh(mesh);

            GenerateGCodeForMeshes(meshes);
        }

        static string GenerateGCodeForMeshes(PrintMeshAssembly meshes)
        {

            // configure settings
            //RepRapSettings settings = new RepRapSettings(RepRap.Models.Unknown);
            MakerbotSettings settings = new MakerbotSettings(Makerbot.Models.Replicator2);

            LastSettings = settings.CloneAs<SingleMaterialFFFSettings>();

            MeshPlanarSlicer slicer = new MeshPlanarSlicer()
            {
                LayerHeightMM = settings.LayerHeightMM
            };
            slicer.Add(meshes);
            PlanarSliceStack slices = slicer.Compute();

            SingleMaterialFFFPrintGenerator printGen =
                new SingleMaterialFFFPrintGenerator(meshes, slices, settings);
            if (printGen.Generate())
            {
                // export gcode
                GCodeFile gcode = printGen.Result;
                using (StreamWriter w = new StreamWriter("generated.gcode"))
                {
                    StandardGCodeWriter writer = new StandardGCodeWriter();
                    writer.WriteFile(gcode, w);
                }
            }
            return "";
        }
    }
}`

Even though I'm almost using the exact same code as the one in your tutorial, my result is kinda weird, the following screenshot is the Gcode displayed in PronterFace : 

![image](https://user-images.githubusercontent.com/39619078/40538300-a33957e8-6011-11e8-88c8-7a6482d702cd.png)

So there is space between my layers and it looks like no shells are rendered as you can see here : 

![image](https://user-images.githubusercontent.com/39619078/40538397-e5376ad6-6011-11e8-9105-2c76e8a6c754.png)

The whole slicing looks messed up, Any idea why this happens ?

PS : sorry for bad englendo and formatting!

**Comment by Archerfortx** [comment]
Alright for those wondering about this I solved the issue, 

In fact I analyzed my output Gcode and nothing was really wrong except one thing : 
the gcode Writer in the program uses "," instead of "." for the values, which cuts my values and make the whole line impossible to parse.

I do have little problem still, there is a Z up between the prime and my first layer, so it's kinda air-printing
my object.


```
M190 S70 ;set bed temp C. and wait
M109 S220 ;set extruder temp C. and wait
G21 ;units=mm
G90 ;absolute positions
M82 ;absolute extruder position
M107 ;fan off
G28 X0 Y0 ;home x/y
G28 Z0 ;home z
G92 E0 ;reset extruded length
G0 X290 Y5 Z0.27 F9000 ;start prime
G1 X10 Y5 F1800 E25.14466 ;prime
G1 Z0 F9000 
M117 Print Started 
;layer 0 - 0.27mm
M107 ;fan off
G1 X10 Y5 Z0.27 F2400 E20.64466 ;Retract
G0 X10 Y5 Z0.47 F6000 ;Plane Change
G0 X138.6 Y79.6 F9000 ;Travel
G1 X138.6 Y79.6 F2400 E25.14466 ;End Retract
M106 S255 ;fan on
```

Is there a way to get rid off this annoying layer up there ?

**Comment by rms80** [comment]
actually it's your computer that is using the commas instead of dots =). It's a localization thing that the OS does automatically, but I can override it to always use dots - thanks for debugging.

For the Z-up issue, you are right, it is a bug. My day-to-day printer is a Replicator2 which has a different header that included a Z-home.

I have just checked in fixes for both these issues, however I haven't done a test print of the Z-up fix on a RepRap yet.

**Comment by Archerfortx** [comment]
Yeah that's what I thought for the commas, good to hear. 

Then I'm just gonna switch to MakerBotSettings and see if it is alright for my printer, since i'm not using a RepRap Machine.

Thanks for the answer !

**Comment by rms80** [comment]
The makerbot header has special commands that aren't going to work on non-makerbot printers. What do you have? If you can give me a sample GCode file for a simple shape (eg cube or cylinder), and are willing to test a bit, I would try to add support for it.

**Comment by Archerfortx** [comment]
The RepRap settings are completly compatible, and I'm using a printer based on Marlin firmware.

I've been testing to slice a Tardis stl from thingyverse and the result is really good, only the fact that after the little prime the gCode is moving one layer up  which is annoying.
I resolved the problem myself by opening the file and replacing the Z values soustracting -0.2 each time the algorithm detect a layer Up.

I don't think it's worth your time to add the support for this printer imo.

![img_20180529_150705](https://user-images.githubusercontent.com/39619078/40660823-72002e7e-6352-11e8-9c95-66a20202b0f5.jpg)

As you can see only my first layer is fucked up 

![img_20180529_150713](https://user-images.githubusercontent.com/39619078/40660883-94bf0606-6352-11e8-88b6-5ad6cbebb15c.jpg)

**Comment by rms80** [comment]
Sorry, just realized I forgot to push the submodule updates that should fix this first-layer issue, and the comma issue. Just updated the gsSlicerApps repo with latest code. 

These are the first prints anyone else besides me have done with the slicer, so, exciting!! If it is a commercial printer that people can buy then even if I don't have to do anything specific, it is good to be able to include it in the list of 'printers that work'...

I should add additional setting flags for the fan, has not been something I thought about so far. In SingleMaterialFFFCompiler.cs, there is call to Assembler.DisableFan() on line 103, if you comment that out then the fan will not be cycled (and maybe also Assembler.EnableFan() on 121).

**Comment by Archerfortx** [comment]
Awesome it's working like a charm now !

So, the Model name is HD from a little french company called Alchimies-OpenEdge if you wanna add up on the working list.

Also I was wondering if you were thinking about implementing others infill patterns any time in the future ? (or is it something that I missed lmao)

Thanks for all dude !

**Comment by rms80** [comment]
Yes I will implement other infills once I ship the printing tool that is being built on top of this slicer, at minimum a diamond-infill. Any other requests? I am kind of more interested in structural integrity than cool patterns/etc.

**Comment by Archerfortx** [comment]
Okay cool stuff ! 

Personally I'm interested in Honeycomb pattern, it seems to be the most viable way to infill objects imo.
