### ISSUE TITLE
slicing parameters 

### ISSUE THREAD

**Issue by gabykl** [gradientspace/gsSlicer#7]
hi, 
i need some assistance in understanding following parameters : 
- PathDefaultWidthMM
- SupportMinZTips
- MinZTipMaxDiam
- MinZTipExtratLayers

what is the use case  for these parameters? 
Regards,

**Comment by rms80** [comment]
Do you mean OpenPathDefaultWidthMM in MeshPlanarSlicer? There is no PathDefaultWidthMM setting in the print settings.... ??   

The one in MeshPlanarSlicer controls the thickness of "open" meshes, ie where just the outline of the mesh is traced, like the fins in this mesh: https://static1.squarespace.com/static/5aef392775f9eee47281d351/t/5af1d12f562fa790d504dab0/1525813883629/open_sheets.png?format=1000w

MinZTips is for supporting the bottom of things like upside-down cones. The standard way we figure out support areas does not find such regions. One way to handle them is to add 'support tip' polygons that get special handling in the toolpathing. These are repeated for several layers to ensure a good connection. However, this doesn't work that well yet except in certain cases and so it is disabled by default and I would suggest you leave it that way.

**Comment by gabykl** [comment]
thanks.

**Comment by gabykl** [comment]
asd
